### ISSUE TITLE
nBytes

### ISSUE THREAD

**Issue by mvahowe** [mvahowe/proskomma-go#10]
The JS implementation is defined at https://github.com/mvahowe/proskomma-utils/blob/051af06f96c0c7722bb31c6c80c9ab8d57b39a71/src/lib/byte_array.js#L120

The idea is to read several nBytes and return their values as an array of integers.

**Comment by chrisvaughn** [comment]
closed by https://github.com/mvahowe/proskomma-go/pull/11
