### ISSUE TITLE
mapVerse

### ISSUE THREAD

**Issue by mvahowe** [mvahowe/proskomma-go#16]
This is more ambitious than the previous issues. It could also be useful as a standalone Go module.

The best place to start is probably https://github.com/mvahowe/proskomma-utils/blob/main/test/code/versification.js which demonstrates and tests the various stages of the JS implementation. For the Go implementation, I think we need
- [x] vrs2json
- [x] reverseVersification
- [x] succinctifyVerseMappings
- [x] mapVerse

but implementing the other steps might be the simplest way to get these working.

Some background...

Verse mapping means getting from, say, book-chapter-verse (bcv)  in KJV to bcv for the Hebrew sources, or for a French Bible. There are several major bcv schemes, and many variations on those schemes. Verse mapping means that parallel texts can be displayed and processed regardless of the numbers shown to the user.

The `vrs` format is used in Paratext, a major Bible editing tool. Recently I produced a JSON representation of this that has been adopted for wider use - https://github.com/Copenhagen-Alliance/versification-specification In the JS code we are only using the mapping section of these files. It is useful to be able to ingest either format, since there's a huge amount of legacy data in `vrs` format, but devs working on new stacks would probably prefer to maintain JSON.

To map between translations, you first run the mapping forward on the first translation to get to a standard versification called "original". Then you run another mapping backwards to get to the second translation. That's where `reverseVersification` comes in. (Note that the forward mapping is one-to-one, while the reverse mapping may be one-to-many, so the format of the JSON representation is slightly different. `succinctifyVerseMappings` handles both format variants.)

In JS we first build a JSON representation that corresponds to the eventual succinct representation using `https://github.com/Copenhagen-Alliance/versification-specification`. This makes `succinctifyVerseMappings` much simpler and also makes debugging much easier. But the Go implementation could potentially skip this step.

We build 2 succinct lookups per chapter - one forward, one backward. If no mapping is found we return a no-op mapping (ie we give back the BCV we received). To turn this in to a one-stop mapping scheme for an entire version, you'd need to store a tree of these mappings, organized by book and then by chapter, and return no-ops where the book or chapter is not in the tree. (That's more or less what Proskomma will do under the hood.)

Rather than trying to do all this in one mega-PR, it might make sense to do one PR for each of the points above, and maybe to add PRs for any intermediate steps.

The shortest route to something that works would be to perform the `vrs2json` and `reverseVersification` in JS and just implement the succinct aspects in Go. But an all-Go solution would obviously be nicer.

Happy to answer questions about any of this...

**Comment by bhalbright** [comment]
Hi @mvahowe I started on the vrs2json, wanted to get an opinion before I submitted a PR. I didn't get too far ahead so I wasn't sure if I took the right approach, I parsed the vrs into a golang struct instead of a dynamic json object, which I wasn't as sure about using in golang as it seemed harder to work with.

https://github.com/mvahowe/proskomma-go/blob/ba/feature/vrs2json2/versification/versification.go#L24

**Comment by bhalbright** [comment]
just fyi, I did the vrs2json and reverseVersification but I was hesitant to submit a PR in case the approach fell apart when working on the other parts. I'm working on succintifyVerseMappings right now and so far it is okay I think

**Comment by bhalbright** [comment]
closed by #19
